In [3]:
import pickle
import pandas as pd
import numpy as np

In [5]:
f = open( "data.p", "rb" )

datas = pickle.load( f )

ValueError: unsupported pickle protocol: 5

In [1]:
import pickle5 as pickle
with open("data.p", "rb") as fh:
  data = pickle.load(fh)

In [8]:
# cols = data.columns
data2 = data.dropna()

In [3]:
pd.read_csv("./Simu/Data_100/r1_1_1.csv")

0
0     -0.057778
1     -0.119094
2      0.032087
3      0.014969
4     -0.047832
...         ...
35995 -0.056369
35996 -0.010994
35997 -0.032337
35998  0.113442
35999 -0.008675

[36000 rows x 1 columns]

In [2]:
a=np.array([1,2,3,4])

In [3]:
b=a

In [4]:
b[3]=2

In [5]:
a

array([1, 2, 3, 2])

In [7]:
c=a.copy()

In [8]:
c[3]=1

In [9]:
a

array([1, 2, 3, 2])

In [10]:
len(a)

4

In [11]:
a

array([1, 2, 3, 2])

In [12]:
a.size

4

In [13]:
a

array([1, 2, 3, 2])

In [4]:
x = np.array([[1,2],[3,4]])

In [7]:
x

array([[1, 2],
       [3, 4]])

In [16]:
4*x+2

array([[ 6, 10],
       [14, 18]])

In [17]:
x[1]

array([3, 4])

In [21]:
x[:,1].shape

(2,)

In [20]:
a[:,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [22]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [2]])

In [23]:
x.reshape(-1)

array([1, 2, 3, 4])

In [37]:
np.random.choice(x[1], p=[0.3,0.7])

3

In [30]:
x[1]

array([3, 4])

In [46]:
np.cov([1,2,3], [1,3,3])/(np.std([1,2,3])*np.std([1,3,3]))

array([[1.29903811, 1.29903811],
       [1.29903811, 1.73205081]])

In [39]:
np.std(a)

0.7071067811865476

In [42]:
np.corrcoef([1,2,3], [1,3,3])

array([[1.       , 0.8660254],
       [0.8660254, 1.       ]])

In [52]:
np.std([1,2,3])**2

0.6666666666666666

In [55]:
np.corrcoef([[1,2,3], [1,3,3]])[0,1]

0.8660254037844387

In [54]:
np.cov([[1,2,3], [1,3,3]])

array([[1.        , 1.        ],
       [1.        , 1.33333333]])

In [13]:
x[0:2]

array([[1, 2],
       [3, 4]])

In [56]:
np.random.rand(20,1)

array([[0.42008049],
       [0.47819266],
       [0.25907098],
       [0.11583346],
       [0.59477683],
       [0.35035063],
       [0.25665116],
       [0.66209196],
       [0.30171681],
       [0.07085374],
       [0.2277781 ],
       [0.54629298],
       [0.06236629],
       [0.94359062],
       [0.67654661],
       [0.69899884],
       [0.36334751],
       [0.7056558 ],
       [0.37609646],
       [0.64211395]])